import Header from "@/components/ui/Header";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Footer from "@/components/ui/Footer";
import { ThemeProvider } from "@/components/theme-provider"
import { TanstackProvider } from "@/components/tanstack-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackProvider>
            <Header />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
            <Toaster />
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
